sudo: false

language: 
    python

python:
    - 3.4

install:
    - pip install -r requirements.txt
    - pip install pytest-cov coverage coveralls
    - python setup.py develop

script:
    py.test --cov-report term-missing --cov hypr

after_success:
    coveralls
